# Modified in the lateos-ai/wal-g fork. Derived from wal-g/wal-g (Apache-2.0). See NOTICE.

x-s3_common_depends: &s3_common_depends
  depends_on:
    - s3
  links:
    - s3

x-s3_throttling_depends: &s3_throttling_depends
  depends_on:
    - s3-for-throttling
  links:
    - s3-for-throttling

services:
  golang:
    build:
      dockerfile: ./docker/golang/Dockerfile
      context: .
    image: wal-g/golang
    container_name: wal-g_golang

  ubuntu:
    build:
      dockerfile: ./docker/ubuntu/Dockerfile
      context: .
    image: wal-g/ubuntu:18.04
    container_name: wal-g_ubuntu

  ubuntu_22_04:
    build:
      dockerfile: ./docker/ubuntu/Dockerfile_22_04
      context: .
    image: wal-g/ubuntu:22.04
    container_name: wal-g_ubuntu_22_04

  swift:
    image: openstackswift/saio:py3
    container_name: wal-g_swift
    hostname: swift
    ports:
      - "8010:8080"

  s3:
    image: minio/minio:RELEASE.2021-06-07T21-40-51Z
    container_name: wal-g_s3
    hostname: s3
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/fullbucket
      &&  mkdir -p /export/fullratingcomposerbucket
      &&  mkdir -p /export/fulldatabasecomposerbucket
      &&  mkdir -p /export/fullcopycomposerbucket
      &&  mkdir -p /export/fullwithoutfilesmetadatabucket
      &&  mkdir -p /export/fullscandeltabucket
      &&  mkdir -p /export/failoverstoragebucket
      &&  mkdir -p /export/partialbucket
      &&  mkdir -p /export/remotebucket
      &&  mkdir -p /export/remotewithoutfilesmetadatabucket
      &&  mkdir -p /export/cryptobucket
      &&  mkdir -p /export/waldeltabucket
      &&  mkdir -p /export/ghostbucket
      &&  mkdir -p /export/compressionbucket
      &&  mkdir -p /export/deleteretainafterbucket
      &&  mkdir -p /export/copyallbucket
      &&  mkdir -p /export/copybackupbucket
      &&  mkdir -p /export/compressionreversebucket
      &&  mkdir -p /export/delete-retain-full-bucket
      &&  mkdir -p /export/delete-retain-full-multist-bucket
      &&  mkdir -p /export/delete-retain-full-multist-fo-bucket
      &&  mkdir -p /export/delete-retain-find-full-bucket
      &&  mkdir -p /export/delete-before-name-find-full-bucket
      &&  mkdir -p /export/delete-before-time-find-full-bucket
      &&  mkdir -p /export/delete-before-permanent-full-bucket
      &&  mkdir -p /export/delete-before-permanent-delta-bucket
      &&  mkdir -p /export/delete-before-permanent-delta-multist-bucket
      &&  mkdir -p /export/delete-before-permanent-delta-multist-fo-bucket
      &&  mkdir -p /export/delete-without-confirm-bucket
      &&  mkdir -p /export/delete-end-to-end-bucket
      &&  mkdir -p /export/delete-end-to-end-fo-bucket
      &&  mkdir -p /export/delete-target-bucket
      &&  mkdir -p /export/delete-target-delta-find-full-bucket
      &&  mkdir -p /export/delete-target-delta-bucket
      &&  mkdir -p /export/delete-target-delta-multist-bucket
      &&  mkdir -p /export/delete-target-delta-multist-fo-bucket
      &&  mkdir -p /export/delete-garbage-bucket
      &&  mkdir -p /export/delete-garbage-multist-bucket
      &&  mkdir -p /export/delete-garbage-multist-fo-bucket
      &&  mkdir -p /export/archivereadyrename
      &&  mkdir -p /export/storagetoolsbucket
      &&  mkdir -p /export/storagetoolsbucket_target
      &&  mkdir -p /export/sttransferfilesbucket
      &&  mkdir -p /export/sttransferfilesfailoverbucket
      &&  mkdir -p /export/transferbackupbucket
      &&  mkdir -p /export/walrestorebucket
      &&  mkdir -p /export/daemonbucket
      &&  mkdir -p /export/backupmarkimpermanentbucket
      &&  mkdir -p /export/backupmarkpermanentnoerrorbucket
      &&  mkdir -p /export/backupmarkpermanentbucket
      &&  mkdir -p /export/backupperftestbucket
      &&  mkdir -p /export/catchupbucket
      &&  mkdir -p /export/fullstreamedbucket
      &&  mkdir -p /export/receivewalbucket
      &&  mkdir -p /export/severaldeltabackupsbucket
      &&  mkdir -p /export/walperftestbucket
      &&  mkdir -p /export/orioledb_compatibility
      &&  mkdir -p /export/orioledb_simple
      &&  mkdir -p /export/orioledb_compressed
      &&  /usr/bin/minio server /export'

  s3-another:
    image: minio/minio:RELEASE.2021-06-07T21-40-51Z
    container_name: wal-g_s32
    ports:
      - "9001:9001"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLEBUTANOHER"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEYBUTANOTHERTOO"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/mysqlcopybackupto
      &&  /usr/bin/minio server /export'

  s3-for-throttling:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    container_name: wal-g_s3_3
    hostname: s3
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      - "MINIO_API_REQUESTS_MAX=0"
      - "MINIO_API_REQUESTS_DEADLINE=0s"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/walperftestbucket
      &&  minio server /export --console-address ":9090"'

  ssh:
    build:
      dockerfile: docker/ssh/Dockerfile
      context: .
    container_name: wal-g_ssh
    ports:
      - "6942:6942"

  pg10:
    build:
      dockerfile: docker/pg/Dockerfile
      context: .
    image: wal-g/pg10
    container_name: wal-g_pg10

  pg10_tests_template:
    build:
      dockerfile: docker/pg_tests/Dockerfile_prefix
      context: .
    image: wal-g/pg10_tests
    container_name: wal-g_pg10_tests_template
    <<: *s3_common_depends

  pg18:
    build:
      dockerfile: docker/pg/Dockerfile
      context: .
      args:
        UBUNTU_TAG: "22.04"
        PG_MAJOR: "18"
        USE_PGDG: "1"
        INSTALL_WALE: "0"
    image: wal-g/pg18
    container_name: wal-g_pg18

  pg18_tests_template:
    build:
      dockerfile: docker/pg_tests/Dockerfile_prefix
      context: .
      args:
        PG_IMAGE: wal-g/pg18:latest
    image: wal-g/pg18_tests
    container_name: wal-g_pg18_tests_template
    <<: *s3_common_depends

  pg15:
    build:
      dockerfile: docker/pg/Dockerfile
      context: .
      args:
        UBUNTU_TAG: "22.04"
        PG_MAJOR: "15"
        USE_PGDG: "1"
        INSTALL_WALE: "0"
    image: wal-g/pg15
    container_name: wal-g_pg15

  pg15_tests_template:
    build:
      dockerfile: docker/pg_tests/Dockerfile_prefix
      context: .
      args:
        PG_IMAGE: wal-g/pg15:latest
    image: wal-g/pg15_tests
    container_name: wal-g_pg15_tests_template
    <<: *s3_common_depends

  pg16:
    build:
      dockerfile: docker/pg/Dockerfile
      context: .
      args:
        UBUNTU_TAG: "22.04"
        PG_MAJOR: "16"
        USE_PGDG: "1"
        INSTALL_WALE: "0"
    image: wal-g/pg16
    container_name: wal-g_pg16

  pg16_tests_template:
    build:
      dockerfile: docker/pg_tests/Dockerfile_prefix
      context: .
      args:
        PG_IMAGE: wal-g/pg16:latest
    image: wal-g/pg16_tests
    container_name: wal-g_pg16_tests_template
    <<: *s3_common_depends

  pg17:
    build:
      dockerfile: docker/pg/Dockerfile
      context: .
      args:
        UBUNTU_TAG: "22.04"
        PG_MAJOR: "17"
        USE_PGDG: "1"
        INSTALL_WALE: "0"
    image: wal-g/pg17
    container_name: wal-g_pg17

  pg17_tests_template:
    build:
      dockerfile: docker/pg_tests/Dockerfile_prefix
      context: .
      args:
        PG_IMAGE: wal-g/pg17:latest
    image: wal-g/pg17_tests
    container_name: wal-g_pg17_tests_template
    <<: *s3_common_depends

  pg10_test_common: &pg10_test_common
    image: wal-g/pg10_tests
    user: postgres
    <<: *s3_common_depends

  pg18_test_common: &pg18_test_common
    image: wal-g/pg18_tests
    user: postgres
    <<: *s3_common_depends

  pg15_test_common: &pg15_test_common
    image: wal-g/pg15_tests
    user: postgres
    <<: *s3_common_depends

  pg16_test_common: &pg16_test_common
    image: wal-g/pg16_tests
    user: postgres
    <<: *s3_common_depends

  pg17_test_common: &pg17_test_common
    image: wal-g/pg17_tests
    user: postgres
    <<: *s3_common_depends

  pg15_full_backup_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_full_backup_test
    command: /tmp/tests/full_backup_test.sh

  pg15_remote_backup_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_remote_backup_test
    command: /tmp/tests/remote_backup_test.sh

  pg15_delete_retain_full_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_delete_retain_full_test
    command: /tmp/tests/delete_retain_full_test.sh

  pg15_catchup_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_catchup_test
    command: /tmp/tests/catchup_test.sh

  pg15_wal_perftest:
    <<: *pg15_test_common
    container_name: wal-g_pg15_wal_perftest
    command: /tmp/tests/wal_perftest.sh

  pg15_crypto_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_crypto_test
    command: /tmp/tests/crypto_test.sh

  pg15_delta_backup_fullscan_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_delta_backup_fullscan_test
    command: /tmp/tests/delta_backup_fullscan_test.sh

  pg15_wale_compatibility_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_wale_compatibility_test
    command: /tmp/tests/wale_compatibility_test.sh

  pg15_config_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_config_test
    command: /tmp/tests/config_test.sh

  pg15_ghost_table_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_ghost_table_test
    command: /tmp/tests/ghost_table_test.sh

  pg15_partial_restore_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_partial_restore_test
    command: /tmp/tests/partial_restore_test.sh

  pg15_prefetch_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_prefetch_test
    command: /tmp/tests/prefetch_test.sh

  pg15_receive_wal_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_receive_wal_test
    command: /tmp/tests/receive_wal_test.sh

  pg15_several_delta_backups_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_several_delta_backups_test
    command: /tmp/tests/several_delta_backups_test.sh

  pg15_full_backup_streamed_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_full_backup_streamed_test
    command: /tmp/tests/full_backup_streamed_test.sh

  pg15_full_backup_copy_composer_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_full_backup_copy_composer_test
    command: /tmp/tests/full_backup_copy_composer_test.sh

  pg15_full_backup_rating_composer_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_full_backup_rating_composer_test
    command: /tmp/tests/full_backup_rating_composer_test.sh

  pg15_full_backup_database_composer_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_full_backup_database_composer_test
    command: /tmp/tests/full_backup_database_composer_test.sh

  pg15_delete_before_permanent_full_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_delete_before_permanent_full_test
    command: /tmp/tests/delete_before_permanent_full_test.sh

  pg15_delete_target_delta_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_delete_target_delta_test
    command: /tmp/tests/delete_target_delta_test.sh

  pg15_delete_garbage_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_delete_garbage_test
    command: /tmp/tests/delete_garbage_test.sh

  pg15_backup_verify_test:
    <<: *pg15_test_common
    container_name: wal-g_pg15_backup_verify_test
    command: /tmp/tests/backup_verify_test.sh

  pg16_full_backup_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_full_backup_test
    command: /tmp/tests/full_backup_test.sh

  pg16_remote_backup_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_remote_backup_test
    command: /tmp/tests/remote_backup_test.sh

  pg16_delete_retain_full_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_delete_retain_full_test
    command: /tmp/tests/delete_retain_full_test.sh

  pg16_catchup_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_catchup_test
    command: /tmp/tests/catchup_test.sh

  pg16_wal_perftest:
    <<: *pg16_test_common
    container_name: wal-g_pg16_wal_perftest
    command: /tmp/tests/wal_perftest.sh

  pg16_crypto_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_crypto_test
    command: /tmp/tests/crypto_test.sh

  pg16_delta_backup_fullscan_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_delta_backup_fullscan_test
    command: /tmp/tests/delta_backup_fullscan_test.sh

  pg16_wale_compatibility_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_wale_compatibility_test
    command: /tmp/tests/wale_compatibility_test.sh

  pg16_config_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_config_test
    command: /tmp/tests/config_test.sh

  pg16_ghost_table_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_ghost_table_test
    command: /tmp/tests/ghost_table_test.sh

  pg16_partial_restore_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_partial_restore_test
    command: /tmp/tests/partial_restore_test.sh

  pg16_prefetch_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_prefetch_test
    command: /tmp/tests/prefetch_test.sh

  pg16_receive_wal_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_receive_wal_test
    command: /tmp/tests/receive_wal_test.sh

  pg16_several_delta_backups_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_several_delta_backups_test
    command: /tmp/tests/several_delta_backups_test.sh

  pg16_full_backup_streamed_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_full_backup_streamed_test
    command: /tmp/tests/full_backup_streamed_test.sh

  pg16_full_backup_copy_composer_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_full_backup_copy_composer_test
    command: /tmp/tests/full_backup_copy_composer_test.sh

  pg16_full_backup_rating_composer_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_full_backup_rating_composer_test
    command: /tmp/tests/full_backup_rating_composer_test.sh

  pg16_full_backup_database_composer_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_full_backup_database_composer_test
    command: /tmp/tests/full_backup_database_composer_test.sh

  pg16_delete_before_permanent_full_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_delete_before_permanent_full_test
    command: /tmp/tests/delete_before_permanent_full_test.sh

  pg16_delete_target_delta_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_delete_target_delta_test
    command: /tmp/tests/delete_target_delta_test.sh

  pg16_delete_garbage_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_delete_garbage_test
    command: /tmp/tests/delete_garbage_test.sh

  pg16_backup_verify_test:
    <<: *pg16_test_common
    container_name: wal-g_pg16_backup_verify_test
    command: /tmp/tests/backup_verify_test.sh

  pg17_full_backup_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_full_backup_test
    command: /tmp/tests/full_backup_test.sh

  pg17_remote_backup_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_remote_backup_test
    command: /tmp/tests/remote_backup_test.sh

  pg17_delete_retain_full_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_delete_retain_full_test
    command: /tmp/tests/delete_retain_full_test.sh

  pg17_catchup_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_catchup_test
    command: /tmp/tests/catchup_test.sh

  pg17_wal_perftest:
    <<: *pg17_test_common
    container_name: wal-g_pg17_wal_perftest
    command: /tmp/tests/wal_perftest.sh

  pg17_crypto_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_crypto_test
    command: /tmp/tests/crypto_test.sh

  pg17_delta_backup_fullscan_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_delta_backup_fullscan_test
    command: /tmp/tests/delta_backup_fullscan_test.sh

  pg17_wale_compatibility_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_wale_compatibility_test
    command: /tmp/tests/wale_compatibility_test.sh

  pg17_config_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_config_test
    command: /tmp/tests/config_test.sh

  pg17_ghost_table_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_ghost_table_test
    command: /tmp/tests/ghost_table_test.sh

  pg17_partial_restore_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_partial_restore_test
    command: /tmp/tests/partial_restore_test.sh

  pg17_prefetch_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_prefetch_test
    command: /tmp/tests/prefetch_test.sh

  pg17_receive_wal_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_receive_wal_test
    command: /tmp/tests/receive_wal_test.sh

  pg17_several_delta_backups_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_several_delta_backups_test
    command: /tmp/tests/several_delta_backups_test.sh

  pg17_full_backup_streamed_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_full_backup_streamed_test
    command: /tmp/tests/full_backup_streamed_test.sh

  pg17_full_backup_copy_composer_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_full_backup_copy_composer_test
    command: /tmp/tests/full_backup_copy_composer_test.sh

  pg17_full_backup_rating_composer_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_full_backup_rating_composer_test
    command: /tmp/tests/full_backup_rating_composer_test.sh

  pg17_full_backup_database_composer_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_full_backup_database_composer_test
    command: /tmp/tests/full_backup_database_composer_test.sh

  pg17_delete_before_permanent_full_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_delete_before_permanent_full_test
    command: /tmp/tests/delete_before_permanent_full_test.sh

  pg17_delete_target_delta_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_delete_target_delta_test
    command: /tmp/tests/delete_target_delta_test.sh

  pg17_delete_garbage_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_delete_garbage_test
    command: /tmp/tests/delete_garbage_test.sh

  pg17_backup_verify_test:
    <<: *pg17_test_common
    container_name: wal-g_pg17_backup_verify_test
    command: /tmp/tests/backup_verify_test.sh
  pg10_test_throttling: &pg10_test_throttling
    image: wal-g/pg10_tests
    user: postgres
    <<: *s3_throttling_depends

  pg10_tests:
    <<: *pg10_test_common
    container_name: wal-g_pg10_tests
    command: /tmp/run_integration_tests.sh

  pg10_storage_swift_test:
    image: wal-g/pg10_tests
    container_name: wal-g_pg10_storage_swift_test
    command: /tmp/test_bins/swift.test -test.v
    depends_on:
      - swift
    links:
      - swift
    environment:
      - "PG_TEST_STORAGE=swift"
      - "OS_USERNAME=test:tester"
      - "OS_PASSWORD=testing"
      - "OS_AUTH_URL=http://swift:8080/auth/v1.0"

  pg10_storage_ssh_test:
    image: wal-g/pg10_tests
    container_name: wal-g_pg10_storage_ssh_test
    command: /tmp/test_bins/sh.test -test.v
    depends_on:
      - ssh
    links:
      - ssh
    environment:
      - "PG_TEST_STORAGE=ssh"

  pg10_ready_rename_test:
    <<: *pg10_test_common
    container_name: archiving_ready_rename_test
    command: /tmp/tests/archiving_ready_rename.sh

  pg10_delete_before_permanent_full_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_before_permanent_full_test
    command: /tmp/tests/delete_before_permanent_full_test.sh

  pg10_backup_mark_permanent_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_backup_mark_permanent_test
    command: /tmp/tests/backup_mark_permanent_test.sh

  pg10_backup_mark_permanent_no_error_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_backup_mark_permanent_no_error_test
    command: /tmp/tests/backup_mark_permanent_no_error_test.sh

  pg10_backup_mark_impermanent_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_backup_mark_impermanent_test
    command: /tmp/tests/backup_mark_impermanent_test.sh

  pg10_delete_before_permanent_delta_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_before_permanent_delta_test
    command: /tmp/tests/delete_before_permanent_delta_test.sh

  pg10_delete_before_permanent_delta_multist_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_before_permanent_delta_multist_test
    command: /tmp/tests/delete_before_permanent_delta_multist_test.sh

  pg10_wal_perftest:
    <<: *pg10_test_common
    container_name: wal-g_pg10_wal_perftest
    command: /tmp/tests/wal_perftest.sh

  pg10_wal_perftest_with_throttling:
    <<: *pg10_test_throttling
    container_name: wal-g_pg10_wal_perftest_with_throttling
    command: /tmp/tests/wal_perftest_with_throttling.sh

  pg10_backup_perftest:
    <<: *pg10_test_common
    container_name: wal-g_pg10_backup_perftest
    command: /tmp/tests/backup_perftest.sh

  pg10_delete_before_name_find_full_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_before_name_find_full_test
    command: /tmp/tests/delete_before_name_find_full_test.sh

  pg10_delete_retain_full_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_retain_full_test
    command: /tmp/tests/delete_retain_full_test.sh

  pg10_delete_retain_full_multist_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_retain_full_multist_test
    command: /tmp/tests/delete_retain_full_multist_test.sh

  pg10_delete_retain_after_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_retain_after_test
    command: /tmp/tests/delete_retain_after_test.sh

  pg10_full_backup_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_full_backup_test
    command: /tmp/tests/full_backup_test.sh

  pg10_full_backup_failover_storage_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_full_backup_failover_storage_test
    command: /tmp/tests/full_backup_failover_storages_test.sh

  pg10_full_backup_streamed_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_full_backup_streamed_test
    command: /tmp/tests/full_backup_streamed_test.sh

  pg10_partial_restore_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_partial_restore_test
    command: /tmp/tests/partial_restore_test.sh

  pg10_remote_backup_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_remote_backup_test
    command: /tmp/tests/remote_backup_test.sh

  pg10_remote_backup_without_files_metadata_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_remote_backup_without_files_metadata_test
    command: /tmp/tests/remote_backup_without_files_metadata_test.sh

  pg18_remote_backup_test:
    <<: *pg18_test_common
    container_name: wal-g_pg18_remote_backup_test
    command: /tmp/tests/remote_backup_test.sh

  pg18_remote_backup_without_files_metadata_test:
    <<: *pg18_test_common
    container_name: wal-g_pg18_remote_backup_without_files_metadata_test
    command: /tmp/tests/remote_backup_without_files_metadata_test.sh

  pg18_full_backup_test:
    <<: *pg18_test_common
    container_name: wal-g_pg18_full_backup_test
    command: /tmp/tests/full_backup_test.sh

  pg10_prefetch_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_prefetch_test
    command: /tmp/tests/prefetch_test.sh

  pg10_ssh_backup_test:
    image: wal-g/pg10_tests
    user: postgres
    container_name: wal-g_pg10_ssh_backup_test
    command: /tmp/tests/ssh_backup_test.sh
    depends_on:
      - ssh
    links:
      - ssh

  pg10_receive_wal_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_receive_wal_test
    command: /tmp/tests/receive_wal_test.sh

  pg10_full_backup_copy_composer_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_full_backup_copy_composer_test
    command: /tmp/tests/full_backup_copy_composer_test.sh

  pg10_full_backup_rating_composer_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_full_backup_rating_composer_test
    command: /tmp/tests/full_backup_rating_composer_test.sh

  pg10_full_backup_database_composer_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_full_backup_database_composer_test
    command: /tmp/tests/full_backup_database_composer_test.sh

  pg10_full_backup_without_files_metadata_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_full_backup_without_files_metadata_test
    command: /tmp/tests/full_backup_without_files_metadata_test.sh

  pg10_delete_before_time_find_full_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_before_time_find_full_test
    command: /tmp/tests/delete_before_time_find_full_test.sh

  pg10_delete_without_confirm_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_without_confirm_test
    command: /tmp/tests/delete_without_confirm_test.sh

  pg10_delete_garbage_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_garbage_test
    command: /tmp/tests/delete_garbage_test.sh

  pg10_delete_garbage_multist_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_garbage_multist_test
    command: /tmp/tests/delete_garbage_multist_test.sh

  pg10_delete_target_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_target_test
    command: /tmp/tests/delete_target_test.sh

  pg10_delete_target_delta_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_target_delta_test
    command: /tmp/tests/delete_target_delta_test.sh

  pg10_delete_target_delta_multist_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_target_delta_multist_test
    command: /tmp/tests/delete_target_delta_multist_test.sh

  pg10_delete_target_delta_find_full_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_target_delta_find_full_test
    command: /tmp/tests/delete_target_delta_find_full_test.sh

  pg10_ghost_table_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_ghost_table_test
    command: /tmp/tests/ghost_table_test.sh

  pg10_config_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_config_test
    command: /tmp/tests/config_test.sh

  pg10_copy_all_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_copy_all_test
    command: /tmp/tests/copy_all_test.sh

  pg10_copy_backup_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_copy_backup_test
    command: /tmp/tests/copy_backup_test.sh

  pg10_delete_end_to_end_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_end_to_end_test
    command: /tmp/tests/delete_end_to_end_test.sh

  pg10_delta_backup_fullscan_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delta_backup_fullscan_test
    command: /tmp/tests/delta_backup_fullscan_test.sh

  pg10_several_delta_backups_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_several_delta_backups_test
    command: /tmp/tests/several_delta_backups_test.sh

  pg10_several_delta_backups_reverse_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_several_delta_backups_reverse_test
    command: /tmp/tests/several_delta_backups_reverse_test.sh

  pg10_crypto_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_crypto_test
    command: /tmp/tests/crypto_test.sh

  pg10_delete_retain_find_full_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delete_retain_find_full_test
    command: /tmp/tests/delete_retain_find_full_test.sh

  pg10_delta_backup_wal_delta_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_delta_backup_wal_delta_test
    command: /tmp/tests/delta_backup_wal_delta_test.sh

  pg10_wale_compatibility_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_wale_compatibility_test
    command: /tmp/tests/wale_compatibility_test.sh

  pg10_wale_tablespace_compatibility_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_wale_tablespace_compatibility_test
    command: /tmp/tests/wale_tablespace_compatibility_test.sh
    env_file:
      - docker/common/common_walg.env
      - docker/pg_tests/walg.env

  pg10_tablespace_support_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_tablespace_support_test
    command: /tmp/tests/tablespace_support_test.sh
    env_file:
      - docker/common/common_walg.env
      - docker/pg_tests/walg.env

  pg10_walg_tablespace_restore_spec_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_walg_tablespace_restore_spec_test
    command: /tmp/tests/walg_tablespace_restore_spec_test.sh
    env_file:
      - docker/common/common_walg.env
      - docker/pg_tests/walg.env

  pg10_transfer_backup_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_transfer_backup_test
    command: /tmp/tests/transfer_backup_test.sh

  pg10_catchup_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_catchup_test
    command: /tmp/tests/catchup_test.sh

  pg10_wal_restore_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_wal_restore_test
    command: /tmp/tests/wal_restore_test.sh

  pg10_daemon_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_daemon_test
    command: /tmp/tests/daemon_test.sh

  pg10_daemon_backup_and_restore_test:
    <<: *pg10_test_common
    command: /tmp/tests/daemon_backup_and_restore_test.sh

  pg10_daemon_client_test:
    <<: *pg10_test_common
    command: /tmp/tests/daemon_client_test.sh

  pg10_pgbackrest:
    build:
      dockerfile: docker/pg_tests/Dockerfile_pgbackrest
      context: .
    image: wal-g/docker_pgbackrest

  pg10_pgbackrest_backup_fetch_test:
    image: wal-g/docker_pgbackrest
    user: postgres
    container_name: wal-g_pgbackrest_backup_fetch_test
    command: /tmp/tests/pgbackrest_backup_fetch_test.sh
    <<: *s3_common_depends

  pg10_backup_verify_test:
    <<: *pg10_test_common
    container_name: wal-g_pg10_backup_verify_test
    command: /tmp/tests/backup_verify_test.sh

  orioledb:
    build:
      dockerfile: docker/orioledb/Dockerfile
      context: .
    image: wal-g/orioledb
    user: postgres
    command: /tmp/run_integration_tests.sh
    <<: *s3_common_depends

  st_tests:
    build:
      dockerfile: docker/st_tests/Dockerfile
      context: .
    image: wal-g/st_tests
    container_name: wal-g_st_tests
    env_file:
      - docker/common/common_walg.env
    <<: *s3_common_depends


