#!/bin/bash
# Modified in the lateos-ai/wal-g fork. Derived from wal-g/wal-g (Apache-2.0). See NOTICE.

set -e

readonly CWD=$PWD
readonly OS=$(uname)
readonly ARCH=$(uname -m)
readonly LIBSODIUM_VERSION=${LIBSODIUM_VERSION:-1.0.21}

# Generate walg_config.h with opaque state type, constants, and wrapper function
# declarations for the Go preamble (avoids #include <sodium.h> in Go files).
generate_walg_config() {
	local incdir="$1"
	local libdir="$2"
	local gcc="${CC:-gcc}"
	local src=$(mktemp /tmp/gen_walg_config_XXXXXX.c 2>/dev/null || true)
	local exe=$(mktemp /tmp/gen_walg_config_XXXXXX 2>/dev/null || true)
	local sz=52 abytes=17 hbytes=25 tagf=3

	if [ -n "$src" ] && [ -n "$exe" ]; then
		cat > "$src" <<-'GCCEOF'
#include <stdio.h>
#include <sodium.h>
int main(void) {
	unsigned long long sz = sizeof(crypto_secretstream_xchacha20poly1305_state);
	printf("%llu %u %u %u\n", sz,
		crypto_secretstream_xchacha20poly1305_ABYTES,
		crypto_secretstream_xchacha20poly1305_HEADERBYTES,
		crypto_secretstream_xchacha20poly1305_TAG_FINAL);
	return 0;
}
GCCEOF
		if $gcc -I"$incdir" "$src" -L"$libdir" -lsodium -o "$exe" 2>/dev/null; then
			local out
			out=$("$exe" 2>/dev/null)
			if [ -n "$out" ]; then
				read sz abytes hbytes tagf <<< "$out"
			fi
		else
			echo "warning: walg_config extractor compilation failed; using defaults (libsodium 1.0.21 x86_64)"
		fi
		rm -f "$src" "$exe"
	else
		echo "warning: could not create temp files for walg_config generation; using defaults"
	fi

	cat > tmp/libsodium/include/walg_config.h <<-WALGEOF
#ifndef WALG_CONFIG_H
#define WALG_CONFIG_H

/* Auto-generated by link_libsodium.sh - DO NOT EDIT */

/* Opaque state type matching crypto_secretstream_xchacha20poly1305_state exactly */
typedef struct { unsigned char d[${sz}]; } walg_secretstream_state;

/* Constants */
#define crypto_secretstream_xchacha20poly1305_ABYTES ${abytes}U
#define crypto_secretstream_xchacha20poly1305_HEADERBYTES ${hbytes}U
#define crypto_secretstream_xchacha20poly1305_TAG_FINAL ${tagf}U

/* Wrapper function declarations (walg_init.c is compiled separately by
   link_libsodium.sh and baked into libsodium.a; only wrappers are needed
   here for cgo preamble analysis). */
int walg_sodium_init();
int walg_secretstream_init_push(walg_secretstream_state *, unsigned char *, const unsigned char *);
int walg_secretstream_init_pull(walg_secretstream_state *, const unsigned char *, const unsigned char *);
int walg_secretstream_push(walg_secretstream_state *, unsigned char *, unsigned long long *, const unsigned char *, unsigned long long, const unsigned char *, unsigned long long, unsigned char);
int walg_secretstream_pull(walg_secretstream_state *, unsigned char *, unsigned long long *, unsigned char *, const unsigned char *, unsigned long long, const unsigned char *, unsigned long long);

#endif
WALGEOF
	echo "info: generated tmp/libsodium/include/walg_config.h"
	# Copy into the Go package directory so cgo can #include "walg_config.h"
	# using current-directory lookup, avoiding CGO_CFLAGS include paths that
	# Go 1.25 may sanitize under -mod=vendor.
	mkdir -p internal/crypto/libsodium/gen
	cp tmp/libsodium/include/walg_config.h internal/crypto/libsodium/gen/walg_config.h
	echo "info: copied to internal/crypto/libsodium/gen/walg_config.h for cgo preamble"
}

# Compile and embed walg_init.c into libsodium.a, removing the .c file
# from cgo's purview (Go 1.25 + -mod=vendor does DWARF analysis on .c files
# and chokes on #include <sodium.h>).
build_walg_init() {
	local incdir="$1"
	local libdir="$2"
	local gcc="${CC:-gcc}"

	mkdir -p tmp/libsodium/src
	cat > tmp/libsodium/src/walg_init.c <<-'WALGEOF'
#include <sodium.h>
#include <walg_config.h>

int walg_sodium_init(void) { return sodium_init(); }
int walg_secretstream_init_push(walg_secretstream_state *state, unsigned char *header, const unsigned char *key) {
	return crypto_secretstream_xchacha20poly1305_init_push((crypto_secretstream_xchacha20poly1305_state *)state, header, key);
}
int walg_secretstream_init_pull(walg_secretstream_state *state, const unsigned char *header, const unsigned char *key) {
	return crypto_secretstream_xchacha20poly1305_init_pull((crypto_secretstream_xchacha20poly1305_state *)state, header, key);
}
int walg_secretstream_push(walg_secretstream_state *state, unsigned char *out, unsigned long long *out_len, const unsigned char *in, unsigned long long in_len, const unsigned char *ad, unsigned long long ad_len, unsigned char tag) {
	return crypto_secretstream_xchacha20poly1305_push((crypto_secretstream_xchacha20poly1305_state *)state, out, out_len, in, in_len, ad, ad_len, tag);
}
int walg_secretstream_pull(walg_secretstream_state *state, unsigned char *out, unsigned long long *out_len, unsigned char *tag, const unsigned char *in, unsigned long long in_len, const unsigned char *ad, unsigned long long ad_len) {
	return crypto_secretstream_xchacha20poly1305_pull((crypto_secretstream_xchacha20poly1305_state *)state, out, out_len, tag, in, in_len, ad, ad_len);
}
WALGEOF

	echo "info: compiling tmp/libsodium/src/walg_init.c -> tmp/libsodium/lib/walg_init.o"
	if $gcc -I"$incdir" -I"$incdir/sodium" -c tmp/libsodium/src/walg_init.c -o tmp/libsodium/lib/walg_init.o -fPIC 2>/dev/null; then
		if [ -f tmp/libsodium/lib/libsodium.a ]; then
			echo "info: injecting walg_init.o into libsodium.a"
			( cd tmp/libsodium/lib && ar rcs libsodium.a walg_init.o 2>/dev/null ) || true
		else
			echo "info: libsodium.a not found at link time; walg_init.o left standalone"
			echo "info: compiler may need -lwalg_init or explicit walg_init.o"
		fi
	else
		echo "WARNING: failed to compile walg_init.c; continuing (link step may fail)"
	fi
}

# When a system libsodium-dev (or equivalent) package is installed,
# populate tmp/libsodium/ from it. This lets builds using the libsodium
# build tag find the headers and static library even under -mod=vendor.
# (Go >= 1.21 sanitizes #cgo CFLAGS/LDFLAGS directives; we avoid path
# directives in source and rely on CGO_ENABLED + CGO_CFLAGS/CGO_LDFLAGS
# from the Makefile + this tree.)
if command -v pkg-config >/dev/null 2>&1 && pkg-config --exists libsodium 2>/dev/null; then
	echo "info: system libsodium found via pkg-config"
	INCDIR=$(pkg-config --variable=includedir libsodium 2>/dev/null)
	LIBDIR=$(pkg-config --variable=libdir libsodium 2>/dev/null)

	mkdir -p tmp/libsodium/include tmp/libsodium/lib

	if [ -n "$INCDIR" ] && [ -d "$INCDIR" ]; then
		[ -f "$INCDIR/sodium.h" ] && cp -f "$INCDIR/sodium.h" tmp/libsodium/include/
		[ -d "$INCDIR/sodium" ] && cp -rf "$INCDIR/sodium" tmp/libsodium/include/
	fi

	# Fallback search for common system locations
	if [ ! -f tmp/libsodium/include/sodium.h ]; then
		for d in /usr/include /usr/local/include; do
			if [ -f "$d/sodium.h" ]; then
				cp -f "$d/sodium.h" tmp/libsodium/include/
				[ -d "$d/sodium" ] && cp -rf "$d/sodium" tmp/libsodium/include/
				break
			fi
		done
	fi

	# Extra broad search (covers cases where sodium.h lives in unexpected subdirs)
	if [ ! -f tmp/libsodium/include/sodium.h ]; then
		for candidate in $(find /usr -name sodium.h -type f 2>/dev/null | head -20); do
			# Prefer a top-level sodium.h (not the one inside a sodium/ subdir) for #include <sodium.h>
			if [ -f "$candidate" ] && [[ "$candidate" != */sodium/sodium.h ]]; then
				cp -f "$candidate" tmp/libsodium/include/sodium.h
				break
			fi
		done
	fi

	# Always ensure the sodium/ subdir with detailed headers is present (internal includes use "sodium/...")
	for sdir in "$INCDIR/sodium" /usr/include/sodium /usr/local/include/sodium; do
		if [ -d "$sdir" ]; then
			mkdir -p tmp/libsodium/include
			cp -rf "$sdir" tmp/libsodium/include/ 2>/dev/null || true
			break
		fi
	done

	# Last-resort redirect wrapper so #include <sodium.h> works even if only subdir was found
	if [ ! -f tmp/libsodium/include/sodium.h ] && [ -d tmp/libsodium/include/sodium ]; then
		cat > tmp/libsodium/include/sodium.h << 'EOT'
/* Auto-generated redirect for wal-g libsodium builds (system package layout) */
#include "sodium/sodium.h"
EOT
	fi

	if [ -n "$LIBDIR" ] && [ -d "$LIBDIR" ]; then
		cp -f "$LIBDIR"/libsodium* tmp/libsodium/lib/ 2>/dev/null || true
	fi
	if [ ! -f tmp/libsodium/lib/libsodium.a ]; then
		for d in /usr/lib/x86_64-linux-gnu /usr/lib/aarch64-linux-gnu /usr/local/lib; do
			if [ -f "$d/libsodium.a" ]; then
				cp -f "$d"/libsodium* tmp/libsodium/lib/ 2>/dev/null || true
				break
			fi
		done
	fi

	# Diagnostics + hard verification (prevents silent "info printed, later cgo failure")
	echo "info: pkg-config INCDIR=$INCDIR LIBDIR=$LIBDIR"
	echo "info: libsodium tree after population:"
	ls -lR tmp/libsodium || true
	if [ ! -f tmp/libsodium/include/sodium.h ]; then
		echo "ERROR: failed to populate tmp/libsodium/include/sodium.h"
		echo "Searched candidates:"
		find /usr -name 'sodium.h' 2>/dev/null | head -10 || true
		exit 1
	fi
	if [ ! -f tmp/libsodium/lib/libsodium.a ] && [ ! -f tmp/libsodium/lib/libsodium.so ] && [ ! -f tmp/libsodium/lib/libsodium.dylib ]; then
		echo "WARNING: no libsodium static/shared lib found in tmp/libsodium/lib; link step may fail"
	fi

	# Generate a .pc file so #cgo pkg-config: libsodium resolves through
	# PKG_CONFIG_PATH even when using the tmp/ copy rather than system install.
	mkdir -p tmp/libsodium/lib/pkgconfig
	cat > tmp/libsodium/lib/pkgconfig/libsodium.pc <<- EOT
prefix=$(cd tmp/libsodium && pwd)
libdir=\${prefix}/lib
includedir=\${prefix}/include

Name: libsodium
Version: ${LIBSODIUM_VERSION}
Description: libsodium
Libs: -L\${libdir} -lsodium
Cflags: -I\${includedir}
EOT

	cd "$CWD"
	generate_walg_config "$INCDIR" "$LIBDIR"
	build_walg_init "$INCDIR" "$LIBDIR"
	exit 0
fi

echo "info: no system libsodium, building from source"

test -d tmp/libsodium || mkdir -p tmp/libsodium

cd tmp/libsodium

curl --retry 5 --retry-delay 0 -sL https://github.com/jedisct1/libsodium/releases/download/$LIBSODIUM_VERSION-RELEASE/libsodium-$LIBSODIUM_VERSION.tar.gz -o libsodium-$LIBSODIUM_VERSION.tar.gz
tar xfz libsodium-$LIBSODIUM_VERSION.tar.gz --strip-components=1

CONFIGURE_ARGS="--prefix ${PWD} --disable-debug --disable-dependency-tracking --enable-static --disable-shared"
if [[ "${OS}" == "SunOS" ]]; then
  # On Illumos / Solaris libssp causes linking issues when building wal-g.
  CONFIGURE_ARGS="${CONFIGURE_ARGS} --disable-ssp"
fi   

LOCAL_CFLAGS="-O2"
if [[ "${OS}" == "Linux" ]] && [[ "${ARCH}" == *arm* || "${ARCH}" == "aarch64" ]]; then
  LOCAL_CFLAGS="${LOCAL_CFLAGS} -flax-vector-conversions"
fi

CFLAGS="${LOCAL_CFLAGS}" ./configure ${CONFIGURE_ARGS}
make && make check && make install

# Remove shared libraries for using static
rm -f lib/*.so lib/*.so.* lib/*.dylib

cd ${CWD}

# Verification for the source-build case (should have correct layout from configure --prefix)
echo "info: libsodium tree after source build:"
ls -lR tmp/libsodium || true
if [ ! -f tmp/libsodium/include/sodium.h ]; then
	echo "ERROR: source build did not produce tmp/libsodium/include/sodium.h"
	exit 1
fi
if [ ! -f tmp/libsodium/lib/libsodium.a ]; then
	echo "WARNING: source build did not produce tmp/libsodium/lib/libsodium.a"
fi

INCDIR=$(cd tmp/libsodium/include && pwd)
LIBDIR=$(cd tmp/libsodium/lib && pwd)
generate_walg_config "$INCDIR" "$LIBDIR"
build_walg_init "$INCDIR" "$LIBDIR"
